"""empty message

Revision ID: 2d95e5b43884
Revises: dc83bc83ff9c
Create Date: 2022-03-07 19:52:10.230542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d95e5b43884'
down_revision = 'dc83bc83ff9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=280), nullable=False))
    op.drop_column('user', 'password_hashed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hashed', sa.VARCHAR(length=280), autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
