"""empty message

Revision ID: dc83bc83ff9c
Revises: b0d22d216847
Create Date: 2022-03-07 19:19:56.740045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc83bc83ff9c'
down_revision = 'b0d22d216847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hashed', sa.String(length=280), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', 'name')
    op.drop_column('user', 'password_hashed')
    # ### end Alembic commands ###
